# Generated by Django 4.2.1 on 2023-05-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Мужчина', 'Женщина')], max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Часовой пояс'),
        ),
    ]
