# Generated by Django 4.2.1 on 2023-05-23 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=90, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Десктоп', 'Десктоп'), ('Веб', 'Веб'), ('Mobile', 'Mobile'), ('Оборудование', 'Оборудование'), ('Умные устройства', 'Умные устройства')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Информационные технологии', 'Информационные технологиий'), ('Маркетинг', 'Маркетинг'), ('Дизайн', 'Дизайн')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='LangueProg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C++', 'C++'), ('C#', 'C#'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Базовый', 'Базовый')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Middle+', 'Middle+')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.devices', verbose_name='Устройства'),
        ),
        migrations.AddField(
            model_name='course',
            name='directions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.directions', verbose_name='Направления'),
        ),
        migrations.AddField(
            model_name='course',
            name='lang',
            field=models.ManyToManyField(to='courses.langueprog', verbose_name='Языки Программирования'),
        ),
        migrations.AddField(
            model_name='course',
            name='special',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.special', verbose_name='Уровень'),
        ),
    ]
