# Generated by Django 4.2.1 on 2023-05-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Десктоп', 'Десктоп'), ('Веб', 'Веб'), ('Mobile', 'Mobile'), ('Оборудование', 'Оборудование'), ('Умные устройства', 'Умные устройства')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Информационные технологии', 'Базовый'), ('Маркетинг', 'Маркетинг'), ('Дизайн', 'Дизайн')], max_length=50, verbose_name='Языки программирования')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='special',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.special', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.devices', verbose_name='Устройства'),
        ),
        migrations.AddField(
            model_name='course',
            name='directions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.directions', verbose_name='Направления'),
        ),
    ]
