# Generated by Django 4.2.1 on 2023-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_devices_directions_alter_course_special_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='name',
            field=models.CharField(choices=[('Информационные технологии', 'Информационные технологиий'), ('Маркетинг', 'Маркетинг'), ('Дизайн', 'Дизайн')], max_length=50, verbose_name='Языки программирования'),
        ),
    ]
