# Generated by Django 4.2.1 on 2023-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_option_package_temp_order_directions_order_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Имя фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
