# Generated by Django 4.2.1 on 2023-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_order_email_order_name_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='diplom',
            field=models.CharField(choices=[('В конце обучения', 'В конце обучения'), ('12 месяцев', '12 месяцев')], max_length=90, null=True, verbose_name='Пакет'),
        ),
        migrations.AddField(
            model_name='package',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.special', verbose_name='Знания на выходе'),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.CharField(choices=[('3510', '3510'), ('4052', '4052'), ('5921', '5921')], max_length=90, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AddField(
            model_name='package',
            name='time',
            field=models.CharField(choices=[('12 месяцев', '12 месяцев'), ('24 месяцев', '24 месяцев'), ('36 месяцев', '36 месяцев')], max_length=90, null=True, verbose_name='Срок обучения'),
        ),
    ]
