# Generated by Django 4.2.1 on 2023-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_package_diplom_package_level_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.CharField(choices=[('12500', '12500'), ('30000', '30000'), ('25000', '25000')], max_length=90, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AddField(
            model_name='temp',
            name='price',
            field=models.CharField(choices=[('Бесплатно', 'Бесплатно'), ('1621', '1621')], max_length=90, null=True, verbose_name='Цена в месяц'),
        ),
    ]
