# Generated by Django 4.2.1 on 2023-05-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_order_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course',
        ),
    ]
