# Generated by Django 4.2.1 on 2023-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_typeeducation_order_type_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target',
        ),
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.ManyToManyField(null=True, to='courses.option', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='order',
            name='target',
            field=models.ManyToManyField(null=True, to='courses.target', verbose_name='Цели'),
        ),
    ]
