# Generated by Django 4.2.1 on 2023-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_order_option_alter_order_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='image',
            field=models.ImageField(default=2, upload_to='directions_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directions',
            name='name',
            field=models.CharField(blank=True, choices=[('Информационные технологии', 'Информационные технологиий'), ('Маркетинг', 'Маркетинг'), ('Дизайн', 'Дизайн')], max_length=50, null=True, verbose_name='Языки программирования'),
        ),
    ]
