# Generated by Django 4.2.1 on 2023-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_directions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='image',
            field=models.ImageField(upload_to='static/img/directions_images/', verbose_name='Изображение'),
        ),
    ]
